# Generated by Django 4.2.5 on 2024-06-26 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data_compra',
            field=models.DateField(default=datetime.datetime(2024, 6, 26, 10, 11, 29, 571032, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
