# Generated by Django 4.2.5 on 2024-06-26 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_funcionario_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2024, 6, 26, 10, 45, 22, 667948, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
