# Generated by Django 4.2.5 on 2024-06-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_funcionario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
